### ISSUE TITLE
Issues on port 4000

### ISSUE THREAD

**Issue by jacobabrennan** [Lambda-School-Labs/labs9-map-scratcher#96]
The following error appears multiple times in the console (command line, not browser) when first executing "yarn dev". I think it's related to the use of port 4000 as part of hard-coded URIs throughout the project, when the project itself opens port 1738.

```
(node:1188) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.
0.1:4000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
(node:1188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 2)
(node:1188) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

```

**Comment by jacobabrennan** [comment]
Not a bug. Configuration file was missing. Configuration file is pinned in slack channel, for future reference.
